// The built-in methods guests can reach are a security surface: each type's table is both its
// allowlist and its implementation, and any change to it should be deliberate.
import { describe, expect, it } from "vitest";
import { arrayMethods } from "../src/interpreter/array-methods.js";
import { mapMethods, setMethods, urlSearchParamsMethods } from "../src/interpreter/iteration.js";
import { stringMethods } from "../src/interpreter/string-operations.js";
import { byteMethods } from "../src/stdlib/bytes.js";
import { dateMethods } from "../src/stdlib/date.js";
import { numberMethods } from "../src/stdlib/number.js";
import { regexpMethods, regexpProperties } from "../src/stdlib/regexp.js";
import { urlMethods } from "../src/stdlib/url.js";

describe("built-in allowlists", () => {
  it("lists exactly the reviewed methods for each built-in type", () => {
    const names = Object.fromEntries(
      Object.entries({
        arrayMethods,
        mapMethods,
        setMethods,
        urlSearchParamsMethods,
        stringMethods,
        byteMethods,
        dateMethods,
        numberMethods,
        regexpMethods,
        regexpProperties,
        urlMethods,
      }).map(([table, methods]) => [table, [...methods.names].sort()]),
    );
    expect(names).toMatchInlineSnapshot(`
      {
        "arrayMethods": [
          "at",
          "concat",
          "copyWithin",
          "entries",
          "every",
          "fill",
          "filter",
          "find",
          "findIndex",
          "findLast",
          "findLastIndex",
          "flat",
          "flatMap",
          "forEach",
          "includes",
          "indexOf",
          "join",
          "keys",
          "lastIndexOf",
          "map",
          "pop",
          "push",
          "reduce",
          "reduceRight",
          "reverse",
          "shift",
          "slice",
          "some",
          "sort",
          "splice",
          "toReversed",
          "toSorted",
          "toSpliced",
          "toString",
          "unshift",
          "values",
          "with",
        ],
        "byteMethods": [
          "at",
          "set",
          "slice",
          "subarray",
          "toBase64",
          "toHex",
        ],
        "dateMethods": [
          "getDate",
          "getDay",
          "getFullYear",
          "getHours",
          "getMilliseconds",
          "getMinutes",
          "getMonth",
          "getSeconds",
          "getTime",
          "getTimezoneOffset",
          "getUTCDate",
          "getUTCDay",
          "getUTCFullYear",
          "getUTCHours",
          "getUTCMilliseconds",
          "getUTCMinutes",
          "getUTCMonth",
          "getUTCSeconds",
          "toISOString",
          "toJSON",
          "toString",
          "valueOf",
        ],
        "mapMethods": [
          "clear",
          "delete",
          "entries",
          "forEach",
          "get",
          "has",
          "keys",
          "set",
          "values",
        ],
        "numberMethods": [
          "toExponential",
          "toFixed",
          "toPrecision",
          "toString",
        ],
        "regexpMethods": [
          "exec",
          "test",
          "toString",
        ],
        "regexpProperties": [
          "dotAll",
          "flags",
          "global",
          "ignoreCase",
          "lastIndex",
          "multiline",
          "source",
          "sticky",
          "unicode",
        ],
        "setMethods": [
          "add",
          "clear",
          "delete",
          "difference",
          "entries",
          "forEach",
          "has",
          "intersection",
          "isDisjointFrom",
          "isSubsetOf",
          "isSupersetOf",
          "keys",
          "symmetricDifference",
          "union",
          "values",
        ],
        "stringMethods": [
          "at",
          "charAt",
          "charCodeAt",
          "codePointAt",
          "concat",
          "endsWith",
          "includes",
          "indexOf",
          "lastIndexOf",
          "localeCompare",
          "match",
          "matchAll",
          "normalize",
          "padEnd",
          "padStart",
          "repeat",
          "replace",
          "replaceAll",
          "search",
          "slice",
          "split",
          "startsWith",
          "substr",
          "substring",
          "toLowerCase",
          "toString",
          "toUpperCase",
          "trim",
          "trimEnd",
          "trimLeft",
          "trimRight",
          "trimStart",
        ],
        "urlMethods": [
          "toJSON",
          "toString",
        ],
        "urlSearchParamsMethods": [
          "append",
          "delete",
          "entries",
          "forEach",
          "get",
          "getAll",
          "has",
          "keys",
          "set",
          "sort",
          "toString",
          "values",
        ],
      }
    `);
  });
});
